version: "3"
services:
  petcare_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DOCKER_DB_URL_PETCARE}
      DB_USER: ${DOCKER_DB_USER_PETCARE}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD_PETCARE}
    restart: always
    depends_on:
      db_petcare:
        condition: service_healthy

  db_petcare:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PETCARE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PETCARE}
      MYSQL_DATABASE: ${MYSQL_DATABASE_PETCARE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost"]
      timeout: 10s

      retries: 10
